version: '3'
services:
  frontend:
    build: podcast-client/.
    volumes:
      - ./podcast-client/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  backend:
    build: podcast/.
    volumes:
      - ${KUBECONFIG}
